%% Quality Assessment Figure
function [proceed] = QAF(x,lamina_img,spinous_bw,Lamin_model,norm_Metrics,soundp,fs)
% Function creates Quality Assessment for Laminectomy.
% Inputs:
% x: user's data
% lamina_img: final image of user's lamina
% spinous_bw: black and white image of an undamaged spinous process

%% Computer Vision
% Spinous Process
spinous2 = imcrop(lamina_img,[396 520 220 43]);
spinous_bw2 = rgb2gray(spinous2);
spinous_b{1}= spinous_bw;spinous_b{2}=spinous_bw2;
name{1}='spinous_og';name{2}='spinous_test';clear boxPoints boxFeatures
for i=1:2
    boxPoints.name{i} =  detectSURFFeatures(spinous_b{i},'MetricThreshold',1);
    [boxFeatures.name{i},boxPoints.name{i}] = extractFeatures(spinous_b{i},boxPoints.name{i});
end
boxPairs = matchFeatures(boxFeatures.name{1},boxFeatures.name{2});

if length(boxPairs) < 0.70*boxPoints.name{2}.Count
    outcome_sp=0;
else
    outcome_sp=1;
end


% Facet
% facet2 = imcrop(facet_noblood,[317 605 65 60]);
% facet_bw2 = rgb2gray(facet2);
% facet_b{1} = facet_bw;facet_b{2} =facet_bw2;
% name_f{1}='facet_og';name_f{2}='facet_test';clear boxPoints boxFeatures boxPairs
% for i=1:2
%     boxPoints.name_f{i} =  detectSURFFeatures(facet_b{i},'MetricThreshold',0.1);
%     [boxFeatures.name_f{i},boxPoints.name_f{i}] = extractFeatures(facet_b{i},boxPoints.name_f{i});
% end
%     boxPairs = matchFeatures(boxFeatures.name_f{1},boxFeatures.name_f{2});
% 
% matchedBoxPoints =  boxPoints.name_f{1}(boxPairs(:,1),:);
% matchedBoxPoints4 =  boxPoints.name_f{2}(boxPairs(:,2),:);
% figure;
% showMatchedFeatures(facet_bw,facet_bw2,matchedBoxPoints,...
%     matchedBoxPoints4,'montage');

%% QAF Feedback
Safety = sum(Lamin_model.ClassificationSVM.Beta(8) .* ((norm_Metrics(8)-Lamin_model.ClassificationSVM.Mu(8))/Lamin_model.ClassificationSVM.KernelParameters.Scale));
Safety4plot = -Safety;

%title
f1=figure('Position',[1921 361 1365 720]);
figure(f1);subplot(5,2,[1,2]);
plot(1,1);axis off;title('Safety Assessment','FontSize',40);


subplot(5,2,[3,5,7,9]);
plot(1,1);hold on;axis off;
proceed=0;
text(0.9,1.6,'Spinous Process',...
    'FontSize',25,...
    'HorizontalAlignment','right');
if outcome_sp == 0
    text(1.1,1.6,'Damaged',...
    'Color','red',...
    'FontSize',25,...
    'FontWeight','bold',...
    'HorizontalAlignment','left');
elseif outcome_sp == 1
    text(1.1,1.6,'Intact',...
    'Color','g',...
    'FontSize',25,...
    'FontWeight','bold',...
    'HorizontalAlignment','left');
    proceed = proceed+1;
end
text(0.9,1.3,'Dura',...
    'FontSize',25,...
    'HorizontalAlignment','right');
if x.Volume_ofLabel4_SpinalCord(end) == x.Volume_ofLabel4_SpinalCord(1)
    text(1.1,1.3,'Intact',...
    'Color','g',...
    'FontSize',25,...
    'FontWeight','bold',...
    'HorizontalAlignment','left');
    proceed = proceed+1;
else
    text(1.1,1.3,'Damaged',...
    'Color','red',...
    'FontSize',25,...
    'FontWeight','bold',...
    'HorizontalAlignment','left');
end
text(0.9,1,'Other Vertebra',...
    'FontSize',25,...
    'HorizontalAlignment','right');
if x.Volume_ofLabel5_VertebraOtherThanL3(end) == x.Volume_ofLabel5_VertebraOtherThanL3(1)
    text(1.1,1,'Intact',...
    'Color','g',...
    'FontSize',25,...
    'FontWeight','bold',...
    'HorizontalAlignment','left');
    proceed = proceed+1;
else
    text(1.1,1,'Damaged',...
    'Color','r',...
    'FontSize',25,...
    'FontWeight','bold',...
    'HorizontalAlignment','left');
end
% text(0.9,0.7,'Ligamentum Flavum',...
%     'FontSize',25,...
%     'HorizontalAlignment','right');
% if x.Volume_ofLabel7_FlaviumLigamentBetweenL5AndL4(end) == x.Volume_ofLabel7_FlaviumLigamentBetweenL5AndL4(1)
%     if x.Volume_ofLabel8_FlaviumLigamentBetweenL4AndL3(end) == x.Volume_ofLabel8_FlaviumLigamentBetweenL4AndL3(1)
%         if x.Volume_ofLabel9_FlaviumLigamentBetweenL3AndL2(end) == x.Volume_ofLabel9_FlaviumLigamentBetweenL3AndL2(1)
%             text(1.1,0.7,'Intact',...
%             'Color','g',...
%             'FontSize',25,...
%             'FontWeight','bold',...
%             'HorizontalAlignment','left');
%             proceed = proceed+1;
%         else
%             text(1.1,0.7,'Damaged',...
%             'Color','r',...
%             'FontSize',25,...
%             'FontWeight','bold',...
%             'HorizontalAlignment','left');
%         end
%     else
%         text(1.1,0.7,'Damaged',...
%         'Color','r',...
%         'FontSize',25,...
%         'FontWeight','bold',...
%         'HorizontalAlignment','left');
%     end
% else
%     text(1.1,0.7,'Damaged',...
%     'Color','r',...
%     'FontSize',25,...
%     'FontWeight','bold',...
%     'HorizontalAlignment','left');
% end

subplot(5,2,[4,6,8,10]);
plot(1,1);hold on;axis off;title({'Force Applied on','Ligamentum Flavum'},'FontSize',20);
patch([0,1,1,0],[0,0,-10,-10],[152/256,251/256,152/256]);  
patch([0,1,1,0],[0,0,10,10],[255/256,102/256,102/256]);
line([0,1],[0 0]);
set(findall(gca, 'Type', 'Line'),'LineWidth',4);
line([0,1],[-0.2265 -0.2265],'LineStyle','--'); % real metric is positive
scatter(0.5,Safety4plot,90,'o','filled','w');
ylim([-2,2]);hold on;set(gca,'XTick',[]);
if Safety4plot < -2
    h=annotation('arrow');set(h,'parent',gca,'position',[0.5,-1.5,0,-.5],'Color','w');
elseif Safety4plot > 2
    h=annotation('arrow');set(h,'parent',gca,'position',[0.5,1.5,0,.5],'Color','w');
end
if Safety4plot < 0
%     xlabel({'Good job'},...
%     'Color','green',...
%     'FontSize',10,...
%     'FontWeight','bold',...
%     'HorizontalAlignment','center');
    proceed = proceed+1;
else
    xlabel({'To improve, we suggest reducing','the amount of force which you','apply on the Ligamentum Flavum','with your drill'},...
    'Color','red',...
    'FontSize',10,...
    'FontWeight','bold',...
    'HorizontalAlignment','center');
end


% 
% if proceed < 4
%     subplot(5,2,[3,5,7,9]);
%     text(1,0.4,{'You made some mistakes during your surgery.',...
%         'Your metrics may not be representative of your true',...
%         'performance. We recommend that you focus on improving',...
%         'the quality of your surgery before proceeding to metric',...
%         'assessment.',' ','Press any key to retry.'},...
%     'Color','b',...
%     'FontSize',20,...
%     'HorizontalAlignment','center');
% else
%     subplot(5,2,[3,5,7,9]);
%     text(1,0.4,{'You performed the surgery correctly.',' ',...
%         'Press any key to move on to',...
%         'your metric assessment.'},...
%     'Color','b',...
%     'FontSize',20,...
%     'HorizontalAlignment','center');
% end

f4=figure('Position',[6017 313 1360 768]);
figure(f4);
imshow(lamina_img);
f4.Position=[6017 313 1360 768];

%% Playing Instructions

sound(soundp,fs);
end